config/routes.rb
Rails.application.routes.draw do
  root 'welcome#index'

	get 'search' => 'photos#search'
	post 'search_result' => 'photos#search_photo'
  post 'search_result_json' => 'photos#search_photo_json'

  devise_for :users

  resources :photos
end

app/models/photo.rb
class Photo < ActiveRecord::Base
  has_attached_file :photo, styles: { medium: "500x500>", thumb: "200x200>" }
                    # :storage => :dropbox,
                    # :dropbox_credentials => Rails.root.join("config/dropbox.yml")
  validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
  acts_as_mappable :lat_column_name => :latitude,
                   :lng_column_name => :longitude
  belongs_to :user

  def as_json(options)
    super((options || {}).merge({:methods => [:photo_url, :medium_photo_url, :thumb_photo_url]}))
  end

  def photo_url
    self.photo.url
  end

  def medium_photo_url
    self.photo.url(:medium)
  end

  def thumb_photo_url
    self.photo.url(:thumb)
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def skip_if_logged_in
    if user_signed_in?
      redirect_to photos_path
    end
  end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  before_action :set_photo, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:new, :edit, :create, :update, :destroy]

  # GET /photos
  # GET /photos.json
  def index
    @map = params[:map]
    cond = { published: true }
    cond.merge!({ published: false, user_id: params[:user] }) if params[:user]
    @photos = Photo.where(cond)
  end

  def search
    @photo
    render 'search'
  end

  def search_photo
    if params[:name] && !params[:name].empty?
      @photos = Photo.where("name LIKE ?","%#{params[:name]}%").where(published: true)
    elsif params[:longitude] && params[:latitude] && params[:radius]
      bounds = Geokit::Bounds.from_point_and_radius([ params[:latitude], params[:longitude]], params[:radius])
      @photos = Photo.in_bounds(bounds).all.where(published: true)
    else
      @photos = Photo.all.where(published: true)
    end
    render 'index'
  end


  def search_photo_json
    if params[:name] && !params[:name].empty?
      @photos = Photo.where("name LIKE ?","%#{params[:name]}%").where(published: true)
    elsif params[:longitude] && params[:latitude] && params[:radius]
      bounds = Geokit::Bounds.from_point_and_radius([ params[:latitude], params[:longitude]], params[:radius])
      @photos = Photo.in_bounds(bounds).all.where(published: true)
    else
      @photos = Photo.all.where(published: true)
    end
    render :json => @photos
  end

  # GET /photos/1
  # GET /photos/1.json
  def show
  end

  # GET /photos/new
  def new
    @photo = Photo.new
  end

  # GET /photos/1/edit
  def edit
    @photo = Photo.find(params[:id])
  end

  # POST /photos
  # POST /photos.json
  def create
    @photo = Photo.new(photo_params)
    @photo.published = false
    @photo.user = current_user

    respond_to do |format|
      if @photo.save
        format.html { redirect_to @photo, notice: 'Photo was successfully created.' }
        format.json { render :show, status: :created, location: @photo }
      else
        format.html { render :new }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /photos/1
  # PATCH/PUT /photos/1.json
  def update
    respond_to do |format|
      if @photo.update(photo_params)
        format.html { redirect_to @photo, notice: 'Photo was successfully updated.' }
        format.json { render :show, status: :ok, location: @photo }
      else
        format.html { render :edit }
        format.json { render json: @photo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /photos/1
  # DELETE /photos/1.json
  def destroy
    @photo.destroy
    respond_to do |format|
      format.html { redirect_to photos_url, notice: 'Photo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_photo
    @photo = Photo.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def photo_params
    params.require(:photo).permit(:name, :description, :published, :photo, :latitude, :longitude)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  before_action :skip_if_logged_in

  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PhotoGallery</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, user-scalable=no, initial-scale=1.0, minimum-scale=1.0, maximum-scale=1.0">
  <script src="//maps.google.com/maps/api/js?v=3.18&sensor=false&client=&key=&libraries=geometry&language=&hl=&region="></script>
  <script src="//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js"></script>
  <script src='//google-maps-utility-library-v3.googlecode.com/svn/tags/infobox/1.1.9/src/infobox_packed.js' type='text/javascript'></script> <!-- only if you need custom infoboxes -->
</head>
<body>

<div class="notification">
  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>
</div>

<%= render 'shared/header' %>

<%= yield %>

</body>
</html>

app/views/photos/_form.html.erb
<%= form_for(@photo) do |f| %>
  <% if @photo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@photo.errors.count, 'error') %> prohibited this photo from being saved:</h2>

      <ul>
      <% @photo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class: 'form-control', rows: '4' %>
  </div>
  <% unless @photo.new_record? %>
    <div class="form-group">
      <%= f.check_box :published %><%= f.label :published %>
    </div>
  <% else %>
    <div class="form-group">
      <%= f.file_field :photo %>
    </div>
  <% end %>
  <%= f.gmap_coordinate_picker :zoom_level => 15, :default_coordinates => [10.780260, 106.698522]%>

  <div class="actions">
    <%= f.submit defined?(submit) ? submit : 'Upload', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/photos/_gallery.html.erb
<div class="container">
  <div id="gallery" style="display: none;">
    <% @photos.each do |photo| %>
      <a href="<%= photo_path(photo) %>">
        <img alt="<%= photo.name %>" src="<%= photo.photo.url(:medium) %>" data-image="<%= photo.photo.url %>" data-description="<%= photo.description %>" style="display: none" />
      </a>
    <% end %>
  </div>
</div>

<div class="search-container">
  <div class="container">
    <i class="fa fa-times btn-close"></i>
    <%= form_tag(search_result_path, method: 'POST', class: 'search-form') do %>
        <div id="map" style='width: 100%; height: 500px;'></div>
        <div class="form-group">
          <%= text_field_tag(:name, nil, class: 'form-control', placeholder: 'Photo name', autofocus: 'autofocus') %>
        </div>
        <div class="actions">
          <%= submit_tag "Search", class: 'btn btn-block btn-primary' %>
        </div>
        <%= hidden_field_tag 'latitude'%>
        <%= hidden_field_tag 'longitude'%>
        <%= hidden_field_tag 'radius'%>
    <% end %>
  </div>
</div>

<div class="search-toggle" data-toggle="tooltip" data-placement="left" title="Or press 'S' key"></div>

<script type="text/javascript">
  $(function () {
    // Initialize gallery
    $('#gallery').unitegallery({
      gallery_theme: 'tiles',
      tiles_type: 'nested',
      tile_show_link_icon: true,
      tile_link_newpage: false,
      tiles_nested_optimal_tile_width: 400,
      tiles_space_between_cols: 6,
      tiles_space_between_cols_mobile: 6,
      tiles_min_columns: 1
    });

    // Initialize search
    var $search = $('.search-container');

    function showSearch() {
      $search.addClass('open');
      $search.find('.form-control').first().focus();
      google.maps.event.trigger(handler.getMap(), 'resize');
    }

    function closeSearch() {
      $search.removeClass('open');
    }

    $(document).on('keyup', function (event) {
      if (event.keyCode === 83) { // press 's'
        showSearch();
      } else if (event.keyCode === 27) { // press 'ESC'
        closeSearch();
      }
    });

    $('.btn-close').on('click', closeSearch);

    $('.search-toggle').on('click', function () {
      showSearch();
    });

    // Tooltip
    $('[data-toggle="tooltip"]').tooltip();
  });

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

    circle = handler.addCircle({'lat': 10.779131, 'lng': 106.697319, radius: 804.67200},{ strokeColor: '#3399ff', strokeOpacity: 1, fillColor: 'transparent', editable: true, event: "aaaaa" })
    handler.circle = circle
    handler.circle.getServiceObject().center_changed = function(event) {
      update()
    };
    handler.circle.getServiceObject().radius_changed = function(event) {
      update()
    };
    handler.bounds.extendWith(circle);
    handler.fitMapToBounds()
    handler.getMap().setZoom(15)
    update()

//    real_markers.forEach(function(m, index){
//      google.maps.event.addListener(m.getServiceObject(), 'click', function(object){
//      });
//    });
    google.maps.event.addListener(handler.getMap(), 'click', function( event ){
      if (handler.circle) {
        handler.removeMarker(handler.circle)
      }

      circle = handler.addCircle({'lng': event.latLng.lng(), 'lat': event.latLng.lat(), radius: 804.67200},{ strokeColor: '#3399ff', strokeOpacity: 1, fillColor: 'transparent', editable: true, event: "aaaaa" })
      handler.circle = circle
      handler.circle.getServiceObject().center_changed = function(event) {
        update()
      };
      handler.circle.getServiceObject().radius_changed = function(event) {
        update()
      };
      handler.bounds.extendWith(circle);
      handler.fitMapToBounds()
      update()
    });
  });

  function update() {
    $('#latitude').val(handler.circle.getServiceObject().center.lat());
    $('#longitude').val(handler.circle.getServiceObject().center.lng());
    $('#radius').val(handler.circle.getServiceObject().radius);
  };

</script>

app/views/photos/_map.html.erb
<div class="container location-based">
  <div id="map" style='width: 100%; height: 400px; margin-bottom: 6px;'></div>
  <div id="map_gallery" style="display: none; margin-bottom: 20px;">
    <% @photos.each do |photo| %>
        <a href="<%= photo_path(photo) %>">
          <img alt="<%= photo.name %>" src="<%= photo.photo.url(:thumb) %>" data-image="<%= photo.photo.url %>" data-description="<%= photo.description %>" style="display: none" />
        </a>
    <% end %>
  </div>
</div>
<div class="loading">
  <div class="icon"></div>
</div>


<script type="text/javascript">
  // Initialize gallery
  function initGallery() {
    $('#map_gallery').unitegallery({
      gallery_theme: 'tiles',
      tiles_type: 'nested',
      tile_show_link_icon: true,
      tile_link_newpage: false,
      tiles_nested_optimal_tile_width: 400,
      tiles_space_between_cols: 6,
      tiles_space_between_cols_mobile: 6,
      tiles_min_columns: 1
    });
  }

  initGallery();

  markers = [];
  <% @photos.each do |photo| %>
  markers.push({
    "id": <%= photo.id%>,
    "lat": <%= photo.latitude%>,
    "lng": <%= photo.longitude%>,
    "picture": {
      "url": "<%= image_url('icon/camera_thumb.png') %>",
      "width":  20,
      "height": 20
    },
    "infowindow": "<%= photo.name%>"
  });
  <% end%>
  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){
    real_markers = handler.addMarkers(markers);
    handler.bounds.extendWith(real_markers);
    handler.fitMapToBounds();

    google.maps.event.addListener(handler.getMap(), 'click', function( event ){
      if (handler.circle) {
        handler.removeMarker(handler.circle)
      }

      circle = handler.addCircle({'lng': event.latLng.lng(), 'lat': event.latLng.lat(), radius: 804.67200},{ strokeColor: '#3399ff', strokeOpacity: 1, fillColor: 'transparent', editable: true, event: "aaaaa" })
      handler.circle = circle
      handler.circle.getServiceObject().center_changed = function(event) {
        search()
      };
      handler.circle.getServiceObject().radius_changed = function(event) {
        search()
      };
      handler.bounds.extendWith(circle);
      handler.fitMapToBounds()
      search()
    });
  });

    function search() {
      lat = handler.circle.getServiceObject().center.lat();
      lng = handler.circle.getServiceObject().center.lng();
      radius = handler.circle.getServiceObject().radius;
      search_photo(lat, lng, radius);
    };

    function search_photo(lat, long, radius) {
      $('.loading').hide();
      $.ajax({
        url: "<%= search_result_json_path%>",
        method: "POST",
        data: { longitude : long,
                latitude: lat,
                radius: radius
        },
        dataType: "json"
      }).done(function(photos, status, opt) {
        $('#map_gallery').empty();
        photos.forEach(function (photo) {
          var photoHtml = '<a href="/photos/' + photo.id + '">' +
            '<img alt="' + photo.name + '" src="' + photo.medium_photo_url + '" data-image="' + photo.photo_url + '" data-description="' + photo.description + '" style="display: none" />' +
          '</a>';

          $('#map_gallery').append($(photoHtml));
        });

        initGallery();
      }).always(function () {
        $('.loading').hide();
      });
    }

</script>

app/views/photos/edit.html.erb
<div class="container">
    <%= render 'form', submit: 'Update' %>
</div>

app/views/photos/index.html.erb
<% if @map == 'true' %>
  <%= render 'map'%>
<% else %>
  <%= render 'gallery'%>
<% end %>

app/views/photos/new.html.erb
<div class="container">
    <%= render 'form' %>
</div>

app/views/photos/search.html.erb
<%= form_tag(search_result_path, method: "POST") do %>
  <div style='width: 100%; margin-top: 82px;'>
    <div id="map" style='width: 100%; height: 500px;'></div>
  </div>
  <%= text_field_tag(:name) %>
  <div class="actions">
    <%= submit_tag "Search", class: 'btn btn-primary' %>
  </div>
    <%= hidden_field_tag 'latitude'%>
    <%= hidden_field_tag 'longitude'%>
    <%= hidden_field_tag 'radius'%>

<% end %>


<script type="text/javascript">

  handler = Gmaps.build('Google');
  handler.buildMap({ provider: {}, internal: {id: 'map'}}, function(){

    circle = handler.addCircle({'lat': 10.779131, 'lng': 106.697319, radius: 804.67200},{ strokeColor: '#3399ff', strokeOpacity: 1, fillColor: 'transparent', editable: true, event: "aaaaa" })
    handler.circle = circle
    handler.circle.getServiceObject().center_changed = function(event) {
      update()
    };
    handler.circle.getServiceObject().radius_changed = function(event) {
      update()
    };
    if(navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(handler.map.centerOn(circle));
    }
    handler.bounds.extendWith(circle);
    handler.fitMapToBounds()
    handler.getMap().setZoom(15);
    update()

//    real_markers.forEach(function(m, index){
//      google.maps.event.addListener(m.getServiceObject(), 'click', function(object){
//      });
//    });
    google.maps.event.addListener(handler.getMap(), 'click', function( event ){
      if (handler.circle) {
        handler.removeMarker(handler.circle)
      }

      circle = handler.addCircle({'lng': event.latLng.lng(), 'lat': event.latLng.lat(), radius: 804.67200},{ strokeColor: '#3399ff', strokeOpacity: 1, fillColor: 'transparent', editable: true, event: "aaaaa" })
      handler.circle = circle
      handler.circle.getServiceObject().center_changed = function(event) {
        update()
      };
      handler.circle.getServiceObject().radius_changed = function(event) {
        update()
      };
      handler.bounds.extendWith(circle);
      handler.fitMapToBounds()
      update()
    });
  });

  function update() {
    $('#latitude').val(handler.circle.getServiceObject().center.lat());
    $('#longitude').val(handler.circle.getServiceObject().center.lng());
    $('#radius').val(handler.circle.getServiceObject().radius);
  };

</script>

app/views/photos/show.html.erb
<div class="container image-show">
    <div class="image-info">
        <blockquote class="description">
            <p><%= @photo.description %></p>
             <footer><%= @photo.name %></footer>
        </blockquote>
        <a href="<%= edit_photo_path(@photo) %>" class="photo-edit-link">Edit</a>
    </div>

    <%= image_tag @photo.photo.url %>
</div>

app/views/shared/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="<%= root_path %>">Saigon Photos</a>
    </div>

    <div class="collapse navbar-collapse navbar-right navbar-ex1-collapse">
      <ul class="nav navbar-nav">

        <li class="menuItem"><a href="<%= new_photo_path %>">Upload</a></li>
        <li class="menuItem"><a href="<%= photos_path %>">Gallery</a></li>
        <li class="menuItem"><a href="<%= photos_path(map: true) %>">Discovery</a></li>
        <% if user_signed_in? %>
          <li class="menuItem"><%= link_to 'Review', photos_path(map: false, user: current_user.id) %></li>
          <li class="menuItem"><%= link_to 'Profile', edit_user_registration_path %></li>
          <li class="menuItem"><%= link_to 'Log Out', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li class="menuItem"><a href="<%= new_user_registration_path %>">Sign Up</a></li>
        <% end %>
      </ul>
    </div>

  </div>
</nav>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/welcome/index.html.erb
<!-- Preloader -->
<div id="preloader">
    <div id="status"></div>
</div>

<!-- FullScreen -->
<div class="intro-header">
    <div class="col-xs-12 text-center abcen1">
        <h1 class="h1_home wow fadeIn" data-wow-delay="0.4s">Saigon Photos</h1>
        <h3 class="h3_home wow fadeIn" data-wow-delay="0.6s">Simple & best place for photographers</h3>
        <ul class="list-inline intro-social-buttons">
            <li><a href="<%= new_user_session_path %>" class="btn  btn-lg mybutton_cyano wow fadeIn" data-wow-delay="0.8s"><span class="network-name">Login</span></a>
            </li>
            <li><a href="<%= photos_path %>" class="btn  btn-lg mybutton_standard wow swing wow fadeIn" data-wow-delay="1.2s"><span class="network-name">Go to Gallery</span></a>
            </li>
        </ul>
    </div>
</div>